name: supertpv-branch-server
base: core20 # the base snap is the execution environment for this snap
version: '1.2.6' # just for humans, typically '1.2+git' or '1.3.2'
summary: Bracnh server for SuperTPV
description: |
  Bracnh server for SuperTPV

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures: [amd64]

apps:
  supertpv-branch-server:
    command: wrappers/run
    daemon: simple
    plugs: [network, network-bind]
    environment:
      PYTHONPATH: $SNAP/lib/python3/dist-packages

parts:
  supertpv-branch-server:
    plugin: python
    source: .
    requirements: [requirements.txt]
    stage:
      - -app/env/.Python
      - -app/env/bin/python
      - -app/env/bin/python3
      - -app/env/bin/python3.9
    stage-packages:
      - libpython3.9-stdlib
      - libpython3.9-minimal
      - python3.9-minimal
    build-environment:
      - PYTHONPATH: $SNAPCRAFT_PART_INSTALL/lib/python3/dist-packages:$PYTHONPATH
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/app
      cp -r ./* $SNAPCRAFT_PART_INSTALL/app/

  wrappers:
    plugin: dump
    source: snap_wrap/